version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build --workspace
  
  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +nightly clippy --workspace --all-targets
  
  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  tck:
    desc: Runs the server in release mode and musl target with flags for running TCK test cases
    cmds:
      - cmd: cargo +stable run --release --features=tck --target=x86_64-unknown-linux-musl -- srv -H 127.0.0.1 -D ../tck/TestCases

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test --workspace
